export const ResponseMessage = {
  USER_DOES_NOT_EXISTS_WITH_GIVEN_WALLET_ADDRESS:
    "User with given wallet Address doesn't exists",
  USER_DOES_NOT_EXISTS_WITH_GIVEN_USERNAME:
    "User with given username doesn't exists",
  USER_EXISTS_WITH_GIVEN_EMAIL_ADDRESS:
    'User with given email address already exists',
  USER_EXISTS_WITH_GIVEN_USER_NAME: 'User with given user name already exists',
  USER_LOGGED_OUT: 'User has been Logged Out',

  NOTIFICATION_SETTING_UPDATED: 'notification setting of current user updated',
  GET_NOTIFICATION: 'Returns all notification settings of user',
  INTERNAL_SERVER_ERROR: 'Internal Server Error',
  UNAUTHORIZED: 'Unauthorized',
  CHAIN_DETAILS: 'Chain Details',
  TOKEN_DETAILS: 'Token Details',
  TOKEN_IDS: 'Token Ids',
  USER_CREATED: 'User has been created',
  USER_LOGGED_IN: 'User has been Logged In',
  UNIQUE_CONSTRAINTS_EMAIL: 'Email already exists',
  BAD_REQUEST_UPDATE_ADMIN: 'Bad request for updating Admin',
  MSG_UPDATE_SUCCESS: 'Admin updated succesfully',
  UPDATE_SUCCESS: 'successfully updated',
  UPDATE_FAILED: 'update failed',
  BAD_REQUEST_VALIDATE: 'Bad request in ValidateCustomer',
  FETCH_ERROR: 'Error in fetching the records',
  UNIQUE_CONSTRAINTS_CATEGORY: 'category already exists',
  DELETE_SUCCESS: 'category deleted successfully',
  BAD_REQUEST_DELETE_CATEGORY: 'Bad request for deleting Category',
  NOT_FOUND_CATEGORY: 'category not found',
  UPDATE_SUCCESS_CATEGORY: 'category updated succesfully',
  BAD_REQUEST_UPDATE_CATEGORY: 'Bad request for updating Category',
  NOT_FOUND: 'logged in user details not found',
  LOGIN_ADMIN: 'login as admin',
  INVALID_CRED: 'Invalid credentials',
  CREATE_DESC_ADMIN: 'creates the account and returns created admin',
  ADMIN_NOT_LOGGED_IN: 'In case admin is not logged in',
  CATEGORY_BY_ID: 'Get category by CategoryId',
  LOGGED_IN_ADMIN: 'Get data about current logged in admin',
  UPDATE_CATEGORY: 'Update Category Data',
  ALL_CATEGORIES: 'get all categories',
  ALL_ADMINS: 'get all Admins',
  DELETE_CATEGORY: 'delete Category',
  DESC_CREATE_CATEGORY: 'creates the category and returns created category',
  UPDATE_ADMIN: 'Update Admin Data',
  ADMIN_NOT_FOUND: 'Admin not found**',

  COLLECTION_CREATED: 'Collection Created',
  COLLECTION_CREATION_FAILED: 'Collection creation failed',
  COLLECTIONS_DO_NOT_EXIST: 'Collections do not exist',
  COLLECTION_DOES_NOT_EXIST: 'Collection does not exist',
  COLLECTION_DELETED: 'Collection deleted',

  USER_DOES_NOT_OWN_COLLECTION: 'User does not own the collection',
  REPORTED_COLLECTION: 'Reported Collections',
  REPORTED_ITEM: 'Reported Items',
  REPORTED_USERS: 'Reported Users',

  ACTIVITY_CREATED: 'Activity created',
  ACTIVITY_CREATION_FAILED: 'Activity creation failed',
  ACTIVITIES_DO_NOT_EXIST: 'Activities do not exist',
  ACTIVITY_DOES_NOT_EXIST: 'Activity does not exist',
  ACTIVITY_DELETED: 'Activity deleted',

  COLLABORATOR_ADDED: 'Collaborator added',
  COLLABORATOR_REMOVED: 'Collaborator removed',
  WATCHLIST_ADDED: 'User has been added in Watchlist',
  WATCHLIST_REMOVED: 'User has been removed from watchlist',
  COLLECTION_LIST: 'List of Collections',
  OFFER_CREATED: 'Offer created',
  BAD_REQUEST_OFFER_CREATION: 'Bad request for offer creation',
  BAD_REQUEST_OFFER_UPDATE: 'Bad request for offer update',
  OFFER_REMOVED: 'Offer removed successfully',
  OFFERS_DO_NOT_EXIST: 'Offers do not exist',
  OFFER_ALREADY_EXISTS: 'Offer already exists',
  OFFER_ALREADY_DELETED: 'Offer already removed',
  USER_DOES_NOT_OWN_OFFER: 'User who sent the request doesnt own the offer',
  ITEM_NOT_FOUND: 'Item not found',
  BAD_REQUEST: 'Bad request',
  USER_DOES_NOT_OWN_ITEM: 'User does not own the item',
  ITEM_ACTIVITIES: 'Item Activities',
  ACTIVITIES: 'Activities',
  UNIQUE_CONSTRAINTS_NAME: 'Name and URL of the collection must be unique',

  COLLECTION_NAME: 'Collection Name is Empty',
  UNIQUE_COLLECTION_CHECK: 'Boolean Values for Collection Name and url',
  OWNER_CANNOT_BE_ADDED_AS_COLLABORATOR:
    'Owner cannot be added in collaborators',
  COLLABORATOR_ADD_FAILED: 'Collaborator addition failed',
  USER_ALREADY_IN_COLLABORATORS: 'User already in collaborators',
  USER_ALREADY_BLOCKED: 'User is already blocked',
  USER_IS_NOT_BLOCKED: 'User is not blocked',
  SELECT_COLLECTION: 'Please select a collection',
  USER_DETAILS: 'User Details',
  USER_NOT_FOUND: 'User not found',

  AUCTION_DETAILS: 'Auction Details',
  USER_DOSENT_OWN_ALL_ITEM: 'User dosent own all item in collection',
  FAVOURITES_ADDED: 'User has been added in Favourites',
  FAVOURITES_REMOVED: 'User has been removed from Favourites',
  UPDATION_ERROR_FEES: 'Error in updating fees paid',
  FEES_NOT_PAID:
    'Pay firsttime fees. If paid already wait for some time to reflect in blockchain',
  ITEM_IS_FREEZED: 'Can not update item is Freezed',
  ITEM_DELETED: 'Item is deleted',
  ITEM_TRANSFERED: 'Item transfered',
  BAD_REQUEST_TRANSFER: 'Bad request transfer',
  AUCTION_CANCELLED: 'Auction Cancelled',
  AUCTION_CANNOT_BE_CANCELLED: 'Auction cannot be Cancelled',
  ITEMS_LIST: 'List of Items',
  TOKENS_NOT_FOUND: 'Tokens not found',
  SUPPLY_ERROR: 'You dont have enough supply',
  USER_ACTIVITIES: 'User Activities',
  CATEGORY_NOT_FOUND: 'Unable to find category. Please check details.',
  ITEM_TRANSFER_BLOCKCHAIN_ERROR: 'item failed to transfer from blockchain',
  ITEM_DELETE_BLOCKCHAIN_ERROR: 'item failed to delete from blockchain',
  ITEM_UPDATED: 'item updated',
  ITEM_HAS_BEEN_HIDDEN: 'Item has been Hidden',
  ITEM_HAS_BEEN_REMOVED_FROM_HIDDEN: 'Item has been removed from Hidden',
  ITEM_DOES_NOT_BELONG_TO_OWNER: 'Item does not belong to owner',
  ITEM_DETAILS: 'Item Details',

  ITEMS_FAVOURITE_COUNT: 'Items Favourite Count',
  AUCTION_SIGNATURE_UPDATED: 'Auction Signature has been updated',
  OFFER_SIGNATURE_UPDATED: 'Offer Signature has been updated',

  REQUEST_REPORTED: 'request successfully reported',
  ALREADY_REPORTED: 'user have already reported this',
  QUANTITY_EXCEEDS_SUPPLY: 'quantity exceeds supply',
  FETCH_STATS_ADMIN: 'fetched stats for admin',

  TRACK_META_TRANSACTION: 'Track meta Tractions',

  AUCTION_NOT_RESERVED_FOR_CURRENT_BUYER:
    'This auction is not reserved for current Buyer',
  USER_ADDED: 'This user added on SendGrid',
  USER_BANNED: 'User has been banned from platform',
  USER_BLOCKED: 'User has been blocked',
  CASHBACK_PLATFORMFEE: 'Get default cashback and Platformfee',
  BATCH_NFTITEM_CREATED: 'A batch of Nft Item created',
  BUNDLE_MUST_CONSIST_ITEMS: 'Bundle must consist items',
  COLLECTION_IS_BLOCKED: 'Collection is blocked first unblock it',
  COLLECTION_IS_UPDATED: 'Collection is updated',
  COLLECTION_OFFER_PRICE_UPDATED: 'Collection Offer Price Updated',

  EMAIL_VERIFIED: 'Email has been Verified',
  EMAIL_NOT_VERIFIED: 'Email cannot be verified',
  AXIOS_REQUEST_FAILED: 'Axios request failed',
  AU10TIX_INVALID_REQUEST_ID: 'Invalid request id',
  KYC_ALREADY_VERIFIED: 'KYC already verfied',
  KYC_SUBMIT_FAILED: 'KYC submition failed',
  KYC_REQUIRED_DOCUMENTS: 'Please provide all necessory documents',
  KYC_SESSION_GENERATION_FAILED: 'Session generation failed',
  KYC_ACCESSTOKEN_GENERATION_FAILED: 'Access token generation failed',
  KYC_ID_UPDATE_FAILED: 'Unable to update the kyc id',
  UNABLE_TO_FETCH_KYC: 'Unable to fetch data from au10tix',
  COMPLETE_KYC: 'Please complete your kyc first',
  KYC_DELETE_FAILED: 'Unable to delete kyc data from au10tix',
  KYC_DELETE_FAILED_JUNGLE: 'KYC removed from au10tix but not from jungle',
  KYC_REQUEST_LIMIT_EXCEEDED: 'Your kyc request limit has been exceeded',
  AUCTION_LISTING_CANCELLED: 'Auctions Listings Cancelled',
  OFFER_CANCELLED: 'Offers Cancelled',

  UPDATE_KYC: 'apply for KYC first',
  UPDATE_COLLECTION_FAILED: 'Verify user first',

  KYC_LIMIT_RESET_SUCCESS: 'Reset Success',
  KYC_LIMIT_RESET_FAILED: 'Reset Failed',

  NOTABLE_DROPS: 'Notable Drops',
  STATUS_CREATED: 'status created',
  VERIFY_USER: 'Verify user first',
  CASHBACK_SHOULD_BE_LESS: 'cashback should be less than platform fee',
  NOTABLE_DROP_NOT_UPDATED: 'Notable drop for collection is Not updated',
  NOTABLE_DROP_UPDATED: 'Notable drop for collection is updated',
  ALREADY_DELETED: 'Already deleted',

  HIGHEST_BIDDER_UPDATED: 'Highest Bidder Details Updated',

  CURRENT_USER_BANNED: 'You are Banned',
  CURRENT_USER_BLOCKED: 'You are Blocked',

  NO_EARNING_WALLET_ADDRESS_FOUND:
    'No Earning Wallet Address found to send the earings to',
  CREATOR_EARNING_EXCEEDS_MAXIMUM_VALUE:
    'Creator earning exceeds the maximum value',
  SIGNATURE_NOT_VALID: 'Signature not valid',

  CATEGORY_DETAILS: 'Category Details',
  MALICIOUS_FILE: 'Malicious File',
  NFT_ITEM_DETAILS: 'NFT Item Details',
  UNAUTHORIZED_NFT_OWNER: 'User is not owner of the NFT',
  UNIQUE_CONSTRAINTS_STATUS: 'General status already present',

  ALREADY_FOLLOWING: 'User is already following',
  SUCCESS_FOLLOW: 'Successfully Followed',
  SUCCESS_UNFOLLOW: 'Successfully Unfollowed',
  ERROR_FOLLOW: 'Error in follow/Unfollow',

  MAX_FEATURED_COLLECTION: 'Maximum only 2 collections can be set as featured',
  COUNT_FOLLOW_UNFOLLOW: 'Can not fetch counts',
  COLLECTIONS_LIST: 'List of Collection',
  COLLECTION_FAVOURITE_COUNT: 'Collection Favourite Count',
  NFT_FOLLOWED: 'NFT followed',
  NFT_UNFOLLOWED: 'NFT unfollowed',
  CREATOR_LIST: 'List of Creators',
  CREATOR_FAVOURITE_COUNT: 'Creator Favourite Count',
};
