export const ResponseMessage = {
  USER_DOES_NOT_EXISTS_WITH_GIVEN_WALLET_ADDRESS:
    "User with given wallet Address doesn't exists",
  USER_DOES_NOT_EXISTS_WITH_GIVEN_USERNAME:
    "User with given username doesn't exists",
  USER_EXISTS_WITH_GIVEN_EMAIL_ADDRESS:
    "User with given email address already exists",
  USER_EXISTS_WITH_GIVEN_USER_NAME: "User with given user name already exists",
  USER_LOGGED_OUT: "User has been Logged Out",

  INTERNAL_SERVER_ERROR: "Internal Server Error",
  UNAUTHORIZED: "Unauthorized",
  USER_CREATED: "User has been created",
  USER_LOGGED_IN: "User has been Logged In",
  UNIQUE_CONSTRAINTS_EMAIL: "Email already exists",
  BAD_REQUEST_UPDATE_ADMIN: "Bad request for updating Admin",
  MSG_UPDATE_SUCCESS: "Admin updated succesfully",
  UPDATE_SUCCESS: "successfully updated",
  UPDATE_FAILED: "update failed",
  BAD_REQUEST_VALIDATE: "Bad request in ValidateCustomer",
  FETCH_ERROR: "Error in fetching the records",
  UNIQUE_CONSTRAINTS_CATEGORY: "category already exists",
  DELETE_SUCCESS: "category deleted successfully",
  BAD_REQUEST_DELETE_CATEGORY: "Bad request for deleting Category",
  NOT_FOUND_CATEGORY: "category not found",
  UPDATE_SUCCESS_CATEGORY: "category updated succesfully",
  BAD_REQUEST_UPDATE_CATEGORY: "Bad request for updating Category",
  NOT_FOUND: "logged in user details not found",
  LOGIN_ADMIN: "login as admin",
  INVALID_CRED: "Invalid credentials",
  BAD_REQUEST: "Bad request",
  UNIQUE_CONSTRAINTS_NAME: "Name and URL of the collection must be unique",
  USER_DETAILS: "User Details",
  USER_NOT_FOUND: "User not found",
};
